// Routes
export * from './app/(auth)/forgot-password/page.jsx'
export { default as LoginPage } from './app/(auth)/login/page.jsx'
export { metadata as loginMetadata } from './app/(auth)/login/page.jsx'
export * from './app/(auth)/magic/page.jsx'
export * from './app/(auth)/reset/page.jsx'
export * from './app/(auth)/sign-up/page.jsx'
export * from './app/(auth)/verify/page.jsx'
export * from './app/home/page.jsx'
export * from './app/profile/page.jsx'
export * from './app/security/page.jsx'
export * from './app/settings/page.jsx'
export * from './app/support/page.jsx'

// Layouts
export * from './app/(auth)/layout.jsx'
export { default as HomeLayout } from './app/home/layout.jsx'
export { metadata as HomeLayoutMetadata } from './app/home/layout.jsx'
export { default as ProfileLayout } from './app/profile/layout.jsx'
export { metadata as ProfileLayoutMetadata } from './app/profile/layout.jsx'
export { default as SecurityLayout } from './app/security/layout.jsx'
export { metadata as SecurityLayoutMetadata } from './app/security/layout.jsx'
export { default as SettingsLayout } from './app/settings/layout.jsx'
export { metadata as SettingsLayoutMetadata } from './app/profile/layout.jsx'
export * from './app/support/layout.jsx'
export { default as SupportLayout } from './app/support/layout.jsx'
export { metadata as SupportLayoutMetadata } from './app/support/layout.jsx'
